### LOG IN
POST http://localhost:8080/login
Content-Type: application/json

{
  "email": "",
  "password": ""
}

### LOG OUT
POST http://localhost:8080/logout
Content-Type: application/json
Authorization: Bearer CfDJ8BwfA8ac6EtInQQGUGZYWK4lYs2ocxFKMUJcL6pKbtLUnM-j3-4Z9mQ9gyUUpiSuWWMB_Rhpt28_HrimgH0QG2K9YnCMcBs8UJxA3-rzZoDvPTdwSiPf4qh5F4UHn2y5YopmxeD3IcQBmI3Puci_AWTihomGvyDohGjNGABo78nd_1pH7O9tj6TfXmXCd7Q3yd06mUsaSsN014JWc7I3aiWhnrjWD9fhkw0Am5zx7rTzaN8x-XzuLD5o-SrQvJVz1_MpSU07vHejXEqL7tdkT_-_jB4PxxC9vqIJmSnMcNzKoLolU_Swncdq6GiZ33hlf8eueWin0jbl5MQoGCHBZ9x35Hg6Y9r7XS5DiIUT5rZIAJ-LAuFnBNuRYxWSYSKZTT1YGFSWOJff_SE6Ns9DCcIWTcybAF9K3zPMaMCP6KvQT80nnG_7x5pIqU-5Q0VzK8L9gVY-EjCPOjQdMNtzJnznP1wpStbXVyxatydCCuvX9eAaqRw7ZEAsd7e2ctKgz5xMu7SfBEtgl5F6Ox-vbsJkaCOSEy1rbF4gqJxXFf-hsbBa2rz8j4kjGGjvP1clcR57YRBAPok8pL21hmcE3gARDcRuxxU1ga8SFHukooFaFip5yIjoSZZsS9IS3A2ZE1sPk2DQOZrDkTe_TlppZ-6SbnLgor-RXMboOLRV1PSyzzePqrglBVFiMKZFWKJHBearerBw\


### GET 
GET http://192.168.1.2:3000/api/blog