name: Deploy Server

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Docker image tag
      run: echo "IMAGE_TAG=$(date +%s)" >> $GITHUB_ENV

    - name: Build and push Docker image
      run: |
        docker build -t dongsinhho/portfolio-server:$IMAGE_TAG ./server/
        echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
        docker push dongsinhho/portfolio-server:$IMAGE_TAG

    # - name: Deploy to server
    #   run: |
    #     ssh -o StrictHostKeyChecking=no user@your-server-ip << 'EOF'
    #     docker pull dongsinhho/portfolio-server:latest
    #     docker stop your-container-name || true
    #     docker rm your-container-name || true
    #     docker run -d --name your-container-name -p 80:80 dongsinhho/portfolio-server:latest
    #     EOF
    #   env:
    #     SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
