name: Deploy Server

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Docker image tag
      run: echo "IMAGE_TAG=$(date +%s)" >> $GITHUB_ENV

    - name: Build and push Docker image
      run: |
        docker build -t dongsinhho/portfolio-server:$IMAGE_TAG ./server/
        echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
        docker push dongsinhho/portfolio-server:$IMAGE_TAG
    - name: Build and push Docker image for Raspbian
      run: |
        docker build --platform linux/arm64/v8 -t dongsinhho/portfolio-server:$IMAGE_TAG ./server/
        echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
        docker push dongsinhho/portfolio-server:raspberry

    # - name: Deploy to server
    #   run: |
    #     ssh -o StrictHostKeyChecking=no user@your-server-ip << 'EOF'
    #     docker pull dongsinhho/portfolio-server:latest
    #     docker stop your-container-name || true
    #     docker rm your-container-name || true
    #     docker run -d -e AllowOrigins__0='https://site1' -e AllowOrigins__1='https://site2' -e AllowOrigins__2='https://site3' -e DBSettings__ConnectionString='cntstring' -e Urls=http://0.0.0.0:3000 -p 3000:3000 --name portfolio-server dongsinhho/portfolio-server:$TAG_NAME
    #     EOF
    #   env:
    #     SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
